from __future__ import annotations

import logging
import shutil
import subprocess
import sys
from pathlib import Path

logger = logging.getLogger(__name__)


_MODELFILE_TEMPLATE = """\
# Modelfile for Qwen3-8B + LoRA adapter ({mode})
# Generated by training/export_to_gguf.py

FROM ./{gguf_filename}

# Inherit Qwen3 chat template
TEMPLATE \"\"\"{{- if .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}{{- range .Messages }}<|im_start|>{{ .Role }}
{{ .Content }}<|im_end|>
{{ end }}<|im_start|>assistant
\"\"\"

PARAMETER stop "<|im_start|>"
PARAMETER stop "<|im_end|>"
PARAMETER temperature 0.1
PARAMETER num_ctx 4096

# Note: this model has been LoRA fine-tuned for {mode} mode.
# It is intended to be used WITHOUT mode-specific system prompts —
# the adapter has learned the desired behavior from training data.
"""


def export(
    adapter_dir: str,
    base_model: str = "Qwen/Qwen3-8B",
    output_dir: str = "training/gguf/output",
    quantization: str = "q4_k_m",
    skip_gguf: bool = False,
    llama_cpp_path: str = "llama.cpp",
) -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)-7s | %(message)s",
        datefmt="%H:%M:%S",
        stream=sys.stdout,
    )

    adapter_path = Path(adapter_dir)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    if not adapter_path.exists():
        raise FileNotFoundError(f"Adapter dir not found: {adapter_dir}")

    meta_path = adapter_path / "training_metadata.json"
    mode = "unknown"
    if meta_path.exists():
        import json

        meta = json.loads(meta_path.read_text())
        mode = meta.get("mode", "unknown")
        logger.info("Adapter metadata: mode=%s, base=%s", mode, meta.get("base_model"))

    merged_dir = output_path / "merged"
    logger.info("Step 1: Merging LoRA adapter into base model")
    logger.info("  Adapter:   %s", adapter_path)
    logger.info("  Base:      %s", base_model)
    logger.info("  Output:    %s", merged_dir)

    try:
        from peft import PeftModel
        from transformers import AutoModelForCausalLM, AutoTokenizer
        import torch
    except ImportError as e:
        raise RuntimeError(
            "Missing dependencies. Install:\n  pip install transformers peft torch"
        ) from e

    logger.info("Using CPU for merge (fp16, ~16 GB RAM required)")
    device_map = None
    dtype = torch.float16

    logger.info("Loading base model (this requires ~16-32 GB RAM)...")
    base = AutoModelForCausalLM.from_pretrained(
        base_model,
        torch_dtype=dtype,
        device_map=device_map,
        trust_remote_code=True,
        low_cpu_mem_usage=True,
    )
    tokenizer = AutoTokenizer.from_pretrained(base_model, trust_remote_code=True)

    logger.info("Loading and merging LoRA adapter...")
    if device_map is None:
        model = PeftModel.from_pretrained(
            base,
            str(adapter_path),
            device_map=None,
            is_trainable=False,
        )
    else:
        model = PeftModel.from_pretrained(base, str(adapter_path))
    merged_model = model.merge_and_unload()

    logger.info("Saving merged model to %s", merged_dir)
    merged_model.save_pretrained(str(merged_dir), safe_serialization=True)
    tokenizer.save_pretrained(str(merged_dir))
    del base, model, merged_model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    if skip_gguf:
        logger.info("--skip-gguf set — done. Merged HF model at %s", merged_dir)
        return

    logger.info("Step 2: Converting to GGUF")

    llama_cpp = Path(llama_cpp_path)
    convert_script = llama_cpp / "convert_hf_to_gguf.py"
    quantize_bin = llama_cpp / "build" / "bin" / "llama-quantize"
    if not quantize_bin.exists():
        quantize_bin = llama_cpp / "llama-quantize"
    if not quantize_bin.exists():
        quantize_bin = llama_cpp / "quantize"

    if not convert_script.exists():
        raise RuntimeError(
            f"llama.cpp convert script not found at {convert_script}.\n"
            f"Clone and build llama.cpp:\n"
            f"  git clone https://github.com/ggerganov/llama.cpp\n"
            f"  cd llama.cpp && cmake -B build && cmake --build build -j\n"
            f"  pip install -r requirements.txt"
        )

    if not quantize_bin.exists():
        raise RuntimeError(f"llama-quantize binary not found in {llama_cpp}")

    f16_gguf = output_path / f"{mode}-f16.gguf"
    logger.info("Converting merged model → f16 GGUF: %s", f16_gguf)
    subprocess.run(
        [
            "python",
            str(convert_script),
            str(merged_dir),
            "--outfile",
            str(f16_gguf),
            "--outtype",
            "f16",
        ],
        check=True,
    )

    quantized_gguf = output_path / f"{mode}-{quantization}.gguf"
    logger.info("Quantizing %s → %s (%s)", f16_gguf.name, quantized_gguf.name, quantization)
    subprocess.run(
        [str(quantize_bin), str(f16_gguf), str(quantized_gguf), quantization],
        check=True,
    )

    f16_gguf.unlink()

    modelfile_path = output_path / "Modelfile"
    modelfile_content = _MODELFILE_TEMPLATE.format(
        mode=mode,
        gguf_filename=quantized_gguf.name,
    )
    modelfile_path.write_text(modelfile_content, encoding="utf-8")

    logger.info("Cleaning up merged HF model directory...")
    shutil.rmtree(merged_dir)

    print("\n" + "=" * 70)
    print("EXPORT COMPLETE")
    print("=" * 70)
    print(f"  Mode:          {mode}")
    print(f"  GGUF file:     {quantized_gguf}")
    print(f"  Modelfile:     {modelfile_path}")
    print()
    print("To deploy in Ollama:")
    print(f"  cd {output_path}")
    print(f"  ollama create qwen3-8b-{mode} -f Modelfile")
    print(f"  ollama run qwen3-8b-{mode}")
    print()


def main() -> None:
    import fire

    fire.Fire(export)


if __name__ == "__main__":
    main()
